spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resume_helper?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5

jwt:
  secret: trsdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdadasdasdasdashgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
  expire: 900000